### ISSUE TITLE
`onebusaway-gtfs-transformer-cli` treats `--transform` as a path parameter

### ISSUE THREAD

**Issue by Aeris1One** [OneBusAway/onebusaway-gtfs-modules#287]
**Summary:** 

5a2e50f69adbcdeed1f4f9ee05936499130521ae seems to have broken argument parsing

`onebusaway-gtfs-transformer-cli` handle args wrongly and recognize `--transform` as an input path parameter
```bash
$ java -jar onebusaway-gtfs-transformer-cli-3.2.3.jar --transform="{'op':'remove','match':{'file':'stops.txt','stop_name':'Stop Name'}}" gtfs-in gtfs-tr
23:35:14 INFO GtfsTransformerMain - input path: --transform={'op':'remove','match':{'file':'stops.txt','stop_name':'Stop Name'}}
23:35:14 INFO GtfsTransformerMain - input path: gtfs-in
23:35:14 INFO GtfsTransformerMain - output path: gtfs-tr
23:35:14 INFO GtfsTransformer - reading gtfs from --transform={'op':'remove','match':{'file':'stops.txt','stop_name':'Stop Name'}}
java.nio.file.NoSuchFileException: --transform={op:remove,match:{file:stops.txt,stop_name:Stop
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:56)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1858)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1491)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:194)
	at org.onebusaway.csv_entities.CsvEntityReader.setInputLocation(CsvEntityReader.java:84)
	at org.onebusaway.gtfs.serialization.GtfsReader.setInputLocation(GtfsReader.java:127)
	at org.onebusaway.gtfs_transformer.GtfsTransformer.readGtfs(GtfsTransformer.java:222)
	at org.onebusaway.gtfs_transformer.GtfsTransformer.run(GtfsTransformer.java:168)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.runApplication(GtfsTransformerMain.java:281)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.run(GtfsTransformerMain.java:117)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.main(GtfsTransformerMain.java:96)
```
Tried with Java 17 and 21. Tried with `--transform` at the end of the command, with an external file (`--transform=transformer.txt`) and a url (`--transform=http://127.0.0.1:8080/transformer.txt`), without assignation sign (`--transform transform.txt`).

Working fine using v3.1.0 or earlier, broken since v3.2.0, leading me to think 5a2e50f69adbcdeed1f4f9ee05936499130521ae broke the argument handling. Building `master` after reverting 5a2e50f69adbcdeed1f4f9ee05936499130521ae ends up with a working build.

**Steps to reproduce:** 

Use `onebusaway-gtfs-transformer-cli` with `--transform` argument.

**Platform:** 
Fedora - Java 17 & 21
Debian - Java 21

**Comment by leonardehrenfried** [comment]
Thanks for the detailed report.

I added a end-to-end test, reverted the upgrade and released a new version.

Please keep reporting problems and send fixes as I'm trying to do a thorough clean up of this library.
