### ISSUE TITLE
Java Beans on Android

### ISSUE THREAD

**Issue by apiote** [OneBusAway/onebusaway-gtfs-modules#96]
**Summary:** 

This library doesn’t work on Android because `java.beans` does not exist

**Steps to reproduce:** 

Create a project in Android Studio and try to run:

```kotlin
val reader = GtfsReader()
reader.setInputLocation(File(context.filesDir, "timetable.zip"))
val store = GtfsDaoImpl()
reader.entityStore = store
reader.run()
```
**Expected behavior:** 

Read the content of the gtfs file.

**Observed behavior:** 

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
                                                                 at org.onebusaway.csv_entities.schema.BeanWrapperFactory.wrap(BeanWrapperFactory.java:37)
                                                                 at org.onebusaway.csv_entities.IndividualCsvEntityReader.readEntity(IndividualCsvEntityReader.java:120)
                                                                 at org.onebusaway.csv_entities.IndividualCsvEntityReader.handleLine(IndividualCsvEntityReader.java:98)
                                                                 at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:157)
                                                                 at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
                                                                 at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
                                                                 at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:172)
                                                                 at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:160)
```

**Platform:** 

Android Studio 3.0.1
Android 7.1
Parabola GNU/Linux-libre
Java 1.8
Kotlin 1.2.21

---

Doesn’t this library work on Android on purpose? If so is there OBA library that does?

**Comment by barbeau** [comment]
If you're talking about loading a GTFS zip file into memory in an Android app, then no, I don't believe there is an OBA library that can do that as of today.  The reason is that these zip files can be pretty big, and typically you don't want to be loading them in their entirety on a mobile device.  There are some libraries [here](https://github.com/CUTR-at-USF/awesome-transit) that load GTFS into a database - you might be able to port some of these to Android.  I looked at offline routing in OTP Android a while back - this might be a good place to start - https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/138.

Generally, though, unless you need offline routing or schedule times, for OBA you probably want to just talk to the OBA REST APIs and grab info on-demand like the OBA Android and iOS apps do.  This library should work on Android for that:
https://github.com/OneBusAway/onebusaway-client-library

I'm going to close this issue because Android support isn't a goal of this project, but please let me know if the above doesn't answer your question.

**Comment by barbeau** [comment]
Also, if you don't want to start from scratch and like the OBA Android app, you might want to consider just creating a white-label version of that app - more info at:
https://github.com/OneBusAway/onebusaway-android/blob/master/REBRANDING.md

**Comment by apiote** [comment]
Thank You.
Unfortunately it’s not the answer I hoped I’d get but it does answer my question and I understand the reasons.

**Comment by barbeau** [comment]
Also - if absolutely you want to roll your own on-device GTFS reader, I'd suggest looking at jackson-dataformats-text for CSV format:
https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv

...and specifically data-binding with schema:
https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv#data-binding-with-schema

You might be able to leverage some of the POJO-ish classes from this library to use with Jackson.

I *believe* this library should work on Android.  If not, you can also look at something like [this](https://github.com/CUTR-at-USF/SiriRestClient/wiki/Modifying-XML-libraries-for-Android) that I used to get XML parsing in Jackson working on Android, and it might work.
